import "server-only";
import { FieldValue, type QueryDocumentSnapshot } from "firebase-admin/firestore";
import { getAdminDb } from "@/lib/admin/firebase/admin";
import { COLLECTIONS } from "./shared";

// Contact-form inbox, stored in the Firestore `contactMessages` collection.
// Replaces the former Sanity `contactMessage` documents: a Sanity dataset is
// public-read, which exposed every visitor's name and email to anyone who
// queried it. Here the only reader/writer is the Admin SDK on the server —
// firestore.rules denies every client — so the data is reachable solely
// through the functions below.
//
// Contract shared by the three functions: "Firebase not configured" is an
// expected state (build, local dev before the project exists) and is reported
// as a falsy/null return, mirroring getStripeClient(); real Firestore
// failures REJECT, and each caller decides how to degrade.
const COLLECTION = COLLECTIONS.contactMessages;

export const MESSAGES_PAGE_SIZE = 25;
// Offset pagination reads (and bills) every skipped document, so bound it.
export const MESSAGES_MAX_PAGE = 200;

// Auto-generated Firestore ids are 20 alphanumerics; this allows any sane
// custom id too. Crucially it excludes "/" — `doc("a/b/c")` would otherwise
// address a document in an arbitrary nested path.
const DOCUMENT_ID_PATTERN = /^[A-Za-z0-9_-]{1,128}$/;

export interface ContactMessageInput {
  name: string;
  email: string;
  message: string;
}

export interface ContactMessage {
  id: string;
  name: string;
  email: string;
  message: string;
  createdAt: Date | null;
  read: boolean;
}

export interface ContactMessagePage {
  messages: ContactMessage[];
  hasNextPage: boolean;
}

/**
 * Stores one validated contact submission. Returns `false` (nothing written)
 * when Firebase isn't configured. Fields are listed explicitly — never
 * spread from the input — so nothing unexpected is persisted, and the
 * timestamp is generated by Firestore, never taken from the client.
 */
export async function saveContactMessage(
  input: ContactMessageInput,
): Promise<boolean> {
  const db = getAdminDb();
  if (!db) {
    return false;
  }

  await db.collection(COLLECTION).add({
    name: input.name,
    email: input.email,
    message: input.message,
    createdAt: FieldValue.serverTimestamp(),
    read: false,
  });

  return true;
}

// Documents are only ever written by saveContactMessage, but they are also
// editable by hand in the Firebase console — so the read path coerces every
// field instead of trusting its shape.
function toContactMessage(doc: QueryDocumentSnapshot): ContactMessage {
  const data = doc.data();
  const createdAt = data.createdAt;

  return {
    id: doc.id,
    name: typeof data.name === "string" ? data.name : "",
    email: typeof data.email === "string" ? data.email : "",
    message: typeof data.message === "string" ? data.message : "",
    // A Firestore Timestamp; duck-typed so a hand-edited field of another
    // type degrades to "no date" instead of throwing.
    createdAt:
      typeof createdAt?.toDate === "function"
        ? (createdAt.toDate() as Date)
        : null,
    read: data.read === true,
  };
}

/**
 * One page of messages, newest first (1-based `page`, out-of-range values
 * fall back to the first page). Fetches one extra document to learn whether
 * a next page exists without a separate count query. Returns `null` when
 * Firebase isn't configured.
 */
export async function listContactMessages(
  page = 1,
): Promise<ContactMessagePage | null> {
  const db = getAdminDb();
  if (!db) {
    return null;
  }

  const safePage =
    Number.isInteger(page) && page >= 1 && page <= MESSAGES_MAX_PAGE ? page : 1;

  const snapshot = await db
    .collection(COLLECTION)
    .orderBy("createdAt", "desc")
    .offset((safePage - 1) * MESSAGES_PAGE_SIZE)
    .limit(MESSAGES_PAGE_SIZE + 1)
    .get();

  return {
    messages: snapshot.docs.slice(0, MESSAGES_PAGE_SIZE).map(toContactMessage),
    hasNextPage: snapshot.docs.length > MESSAGES_PAGE_SIZE,
  };
}

/**
 * How many messages are still unread, for the dashboard. Uses Firestore's
 * count aggregation over `read == false`: one equality filter on one field,
 * served by the automatic single-field index (no composite index), and billed
 * as a handful of index reads instead of one read per message. Returns `null`
 * when Firebase isn't configured; a Firestore failure rejects.
 */
export async function countUnreadMessages(): Promise<number | null> {
  const db = getAdminDb();
  if (!db) {
    return null;
  }

  const snapshot = await db
    .collection(COLLECTION)
    .where("read", "==", false)
    .count()
    .get();

  return snapshot.data().count;
}

/**
 * Flags one message as read. Returns `false` (nothing updated) for a
 * malformed id or when Firebase isn't configured; rejects if the document
 * doesn't exist or Firestore fails.
 */
export async function markContactMessageRead(id: string): Promise<boolean> {
  if (!DOCUMENT_ID_PATTERN.test(id)) {
    return false;
  }

  const db = getAdminDb();
  if (!db) {
    return false;
  }

  await db.collection(COLLECTION).doc(id).update({ read: true });
  return true;
}
