"use server";

import { headers } from "next/headers";
import { saveContactMessage } from "@/lib/admin/data/contact-messages";
import { isRateLimited } from "./rate-limit";
import { validateContactInput } from "./validate";

export interface SubmitContactInput {
  name: string;
  email: string;
  message: string;
  /**
   * Honeypot field. A real visitor never fills it (hidden off-screen,
   * aria-hidden, unreachable by keyboard — see ContactForm.tsx); a filled
   * value is treated as an automated submission.
   */
  honeypot: string;
}

export type SubmitContactResult =
  | { ok: true }
  | { ok: false; error: "validation" | "rate_limit" | "server" };

// Rate-limit key = the client IP, taken ONLY from a header the hosting platform
// itself sets and the caller cannot forge. WHICH header is authoritative
// depends on the platform, because the same header name is trustworthy on one
// host and attacker-controlled on another:
//   - Netlify: `x-nf-client-connection-ip`, set by Netlify's edge. `x-real-ip`
//     is NOT platform-set there, so a caller could send any value in it.
//   - Vercel: `x-real-ip`, set by Vercel's edge to the real client IP.
// The platform comes from `process.env.DEPLOY_PLATFORM`, which next.config.ts
// inlines at BUILD time (Netlify's `NETLIFY` variable only exists during the
// build, never at function runtime).
//
// We deliberately do NOT read `x-forwarded-for` on any platform: its leftmost
// entry is client-appendable, so keying the limiter on it lets an attacker
// send a fresh spoofed value per request and bypass the limit entirely (a
// confirmed bypass — see security review). When the platform is unknown
// (local dev, any other host) or its header is missing, we fall back to a
// single shared bucket, so unattributable requests are limited COLLECTIVELY
// (fails closed) rather than each getting a free pass — and rather than
// letting a forged header on the wrong platform pick the bucket.
function trustedClientIpHeader(): string | undefined {
  switch (process.env.DEPLOY_PLATFORM) {
    case "netlify":
      return "x-nf-client-connection-ip";
    case "vercel":
      return "x-real-ip";
    default:
      return undefined;
  }
}

async function resolveClientIp(): Promise<string> {
  const headerName = trustedClientIpHeader();
  if (!headerName) {
    return "unknown";
  }

  const headerList = await headers();
  const clientIp = headerList.get(headerName)?.trim();

  return clientIp || "unknown";
}

/**
 * Server Action backing ContactForm. Order of guards is deliberate: the
 * honeypot check runs FIRST and short-circuits before touching the rate
 * limiter, so a bot hammering the honeypot can never burn through the
 * rate-limit window of a legitimate visitor sharing the same IP/NAT.
 *
 * Messages are stored in Firestore (lib/admin/data/contact-messages.ts) and
 * read back in the admin panel's "Mensajes" page — no longer in Sanity,
 * whose dataset is public-read and would have exposed every visitor's name
 * and email.
 *
 * Wrapped end-to-end in try/catch so this action can never throw uncaught —
 * every branch, including an unexpected failure, resolves to a typed
 * result. Never logs the caught error (it could embed user input) and never
 * echoes any part of the input back in a result.
 */
export async function submitContact(
  input: SubmitContactInput,
): Promise<SubmitContactResult> {
  try {
    if (input.honeypot) {
      return { ok: true };
    }

    const ip = await resolveClientIp();
    if (isRateLimited(ip)) {
      return { ok: false, error: "rate_limit" };
    }

    const validated = validateContactInput(input);
    if (!validated) {
      return { ok: false, error: "validation" };
    }

    // `false` = Firebase isn't configured (e.g. FIREBASE_* unset): nothing
    // was stored, so this must NOT report success. The timestamp is
    // generated by Firestore itself — a client-supplied time is never used.
    const saved = await saveContactMessage(validated);
    if (!saved) {
      return { ok: false, error: "server" };
    }

    return { ok: true };
  } catch {
    return { ok: false, error: "server" };
  }
}
